# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: My Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  env-inspect:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: see current directory
      run: pwd
    - name: See directory structure
      run: ls -al
    - name: See Node.js version
      run: node -v
    - name: See npm version
      run: npm -v
    - name: Create file
      run: touch newfile.txt > "Hello World"
    - name: List files
      run: ls -la
    - name: See file content
      run: cat newfile.txt
    - name: Move file to moved directory
      run: |
        mkdir moved
        mv newfile.txt moved/
    - name: List files after moved
      run: ls -la
    - name: See moved dir content
      run: ls -la moved/

