# Step 1: Define the name of the workflow
name: Node.js Pull Request Validator

# Step 2: Setup the trigger of the workflow
on:
  pull_request:
    branches: ["dev"]

# Step 3: Configure the jobs for the runner
jobs:
  build:
    runs-on: ubuntu-latest

    # Step 4: Define the steps to be executed on the job
    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies (npm ci)
        run: npm ci

      - name: Nest build
        run: npm run build --if-present

      - name: Log directory structure
        run: ls -al
