# Step 1: Define the name of the workflow
name: Node.js Pull Request Validator

# Step 2: Setup the trigger of the workflow
on:
  pull_request:
    branches: ["dev"]

# Step 2.1 (Optional): Add environment variables
env:
  PORT: 3000
  STAGE: "prod"
  CONTAINER_NAME: "cicd-app"
  DUMMY_ENV_1: ${{ secrets.DUMMY_ENV_1 }}
  DUMMY_ENV_2: ${{ secrets.DUMMY_ENV_2 }}

# Step 3: Configure the jobs for the runner
jobs:
  test:
    runs-on: ubuntu-latest

    # Step 4: Define the steps to be executed on the job
    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies (npm ci)
        run: npm ci

      - name: Nest build
        run: npm run build --if-present

      - name: Log directory structure
        run: ls -al

      - name: Shwing envs (Test purpose)
        run: printenv

      - name: Run tests
        run: npm test

  build:
    timeout-minutes: 10 # Prevent hanging builds
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "PORT=${{ env.PORT }}" >> .env
          echo "STAGE=${{ env.STAGE }}" >> .env
          echo "CONTAINER_NAME=${{ env.CONTAINER_NAME }}" >> .env
          echo "DUMMY_ENV_1=${{ env.DUMMY_ENV_1}}" >> .env
          echo "DUMMY_ENV_2=${{ env.DUMMY_ENV_2}}" >> .env

      - name: Show created .env file (for debug purpose)
        run: cat .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.10.0

      - name: Build image
        run: docker compose -f compose.build.yml build --no-cache
